app_name: "orders"

http:
  addr:
  read_timeout:
  write_timeout:
  idle_timeout:

postgres:
  host:
  port:
  user:
  password:
  dbname:
  sslmode:
  max_conns:
  min_conns:
  conn_life:
  health_ping:

logger:
  level:
  json:
