// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: services/opsassistant/api/opspb/ops.proto

package opspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExplainOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // UUID
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`              // опциональный отвит типа: "почему отменился?"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainOrderRequest) Reset() {
	*x = ExplainOrderRequest{}
	mi := &file_services_opsassistant_api_opspb_ops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainOrderRequest) ProtoMessage() {}

func (x *ExplainOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_opsassistant_api_opspb_ops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainOrderRequest.ProtoReflect.Descriptor instead.
func (*ExplainOrderRequest) Descriptor() ([]byte, []int) {
	return file_services_opsassistant_api_opspb_ops_proto_rawDescGZIP(), []int{0}
}

func (x *ExplainOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ExplainOrderRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type ExplainOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`     // развернутый ответ LLM
	Timeline      string                 `protobuf:"bytes,2,opt,name=timeline,proto3" json:"timeline,omitempty"` // человекочитаемый таймлайн (markdown/JSON)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainOrderResponse) Reset() {
	*x = ExplainOrderResponse{}
	mi := &file_services_opsassistant_api_opspb_ops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainOrderResponse) ProtoMessage() {}

func (x *ExplainOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_opsassistant_api_opspb_ops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainOrderResponse.ProtoReflect.Descriptor instead.
func (*ExplainOrderResponse) Descriptor() ([]byte, []int) {
	return file_services_opsassistant_api_opspb_ops_proto_rawDescGZIP(), []int{1}
}

func (x *ExplainOrderResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *ExplainOrderResponse) GetTimeline() string {
	if x != nil {
		return x.Timeline
	}
	return ""
}

type GetTimelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimelineRequest) Reset() {
	*x = GetTimelineRequest{}
	mi := &file_services_opsassistant_api_opspb_ops_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimelineRequest) ProtoMessage() {}

func (x *GetTimelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_opsassistant_api_opspb_ops_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimelineRequest.ProtoReflect.Descriptor instead.
func (*GetTimelineRequest) Descriptor() ([]byte, []int) {
	return file_services_opsassistant_api_opspb_ops_proto_rawDescGZIP(), []int{2}
}

func (x *GetTimelineRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetTimelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timeline      string                 `protobuf:"bytes,1,opt,name=timeline,proto3" json:"timeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimelineResponse) Reset() {
	*x = GetTimelineResponse{}
	mi := &file_services_opsassistant_api_opspb_ops_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimelineResponse) ProtoMessage() {}

func (x *GetTimelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_opsassistant_api_opspb_ops_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimelineResponse.ProtoReflect.Descriptor instead.
func (*GetTimelineResponse) Descriptor() ([]byte, []int) {
	return file_services_opsassistant_api_opspb_ops_proto_rawDescGZIP(), []int{3}
}

func (x *GetTimelineResponse) GetTimeline() string {
	if x != nil {
		return x.Timeline
	}
	return ""
}

var File_services_opsassistant_api_opspb_ops_proto protoreflect.FileDescriptor

const file_services_opsassistant_api_opspb_ops_proto_rawDesc = "" +
	"\n" +
	")services/opsassistant/api/opspb/ops.proto\x12\x06ops.v1\"L\n" +
	"\x13ExplainOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\"J\n" +
	"\x14ExplainOrderResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12\x1a\n" +
	"\btimeline\x18\x02 \x01(\tR\btimeline\"/\n" +
	"\x12GetTimelineRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"1\n" +
	"\x13GetTimelineResponse\x12\x1a\n" +
	"\btimeline\x18\x01 \x01(\tR\btimeline2\xa1\x01\n" +
	"\fOpsAssistant\x12I\n" +
	"\fExplainOrder\x12\x1b.ops.v1.ExplainOrderRequest\x1a\x1c.ops.v1.ExplainOrderResponse\x12F\n" +
	"\vGetTimeline\x12\x1a.ops.v1.GetTimelineRequest\x1a\x1b.ops.v1.GetTimelineResponseB)Z'./services/opsassistant/api/opspb;opspbb\x06proto3"

var (
	file_services_opsassistant_api_opspb_ops_proto_rawDescOnce sync.Once
	file_services_opsassistant_api_opspb_ops_proto_rawDescData []byte
)

func file_services_opsassistant_api_opspb_ops_proto_rawDescGZIP() []byte {
	file_services_opsassistant_api_opspb_ops_proto_rawDescOnce.Do(func() {
		file_services_opsassistant_api_opspb_ops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_opsassistant_api_opspb_ops_proto_rawDesc), len(file_services_opsassistant_api_opspb_ops_proto_rawDesc)))
	})
	return file_services_opsassistant_api_opspb_ops_proto_rawDescData
}

var file_services_opsassistant_api_opspb_ops_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_opsassistant_api_opspb_ops_proto_goTypes = []any{
	(*ExplainOrderRequest)(nil),  // 0: ops.v1.ExplainOrderRequest
	(*ExplainOrderResponse)(nil), // 1: ops.v1.ExplainOrderResponse
	(*GetTimelineRequest)(nil),   // 2: ops.v1.GetTimelineRequest
	(*GetTimelineResponse)(nil),  // 3: ops.v1.GetTimelineResponse
}
var file_services_opsassistant_api_opspb_ops_proto_depIdxs = []int32{
	0, // 0: ops.v1.OpsAssistant.ExplainOrder:input_type -> ops.v1.ExplainOrderRequest
	2, // 1: ops.v1.OpsAssistant.GetTimeline:input_type -> ops.v1.GetTimelineRequest
	1, // 2: ops.v1.OpsAssistant.ExplainOrder:output_type -> ops.v1.ExplainOrderResponse
	3, // 3: ops.v1.OpsAssistant.GetTimeline:output_type -> ops.v1.GetTimelineResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_opsassistant_api_opspb_ops_proto_init() }
func file_services_opsassistant_api_opspb_ops_proto_init() {
	if File_services_opsassistant_api_opspb_ops_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_opsassistant_api_opspb_ops_proto_rawDesc), len(file_services_opsassistant_api_opspb_ops_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_opsassistant_api_opspb_ops_proto_goTypes,
		DependencyIndexes: file_services_opsassistant_api_opspb_ops_proto_depIdxs,
		MessageInfos:      file_services_opsassistant_api_opspb_ops_proto_msgTypes,
	}.Build()
	File_services_opsassistant_api_opspb_ops_proto = out.File
	file_services_opsassistant_api_opspb_ops_proto_goTypes = nil
	file_services_opsassistant_api_opspb_ops_proto_depIdxs = nil
}
