// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: services/opsassistant/api/opspb/ops.proto

package opspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpsAssistant_ExplainOrder_FullMethodName = "/ops.v1.OpsAssistant/ExplainOrder"
	OpsAssistant_GetTimeline_FullMethodName  = "/ops.v1.OpsAssistant/GetTimeline"
)

// OpsAssistantClient is the client API for OpsAssistant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpsAssistantClient interface {
	ExplainOrder(ctx context.Context, in *ExplainOrderRequest, opts ...grpc.CallOption) (*ExplainOrderResponse, error)
	GetTimeline(ctx context.Context, in *GetTimelineRequest, opts ...grpc.CallOption) (*GetTimelineResponse, error)
}

type opsAssistantClient struct {
	cc grpc.ClientConnInterface
}

func NewOpsAssistantClient(cc grpc.ClientConnInterface) OpsAssistantClient {
	return &opsAssistantClient{cc}
}

func (c *opsAssistantClient) ExplainOrder(ctx context.Context, in *ExplainOrderRequest, opts ...grpc.CallOption) (*ExplainOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainOrderResponse)
	err := c.cc.Invoke(ctx, OpsAssistant_ExplainOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsAssistantClient) GetTimeline(ctx context.Context, in *GetTimelineRequest, opts ...grpc.CallOption) (*GetTimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTimelineResponse)
	err := c.cc.Invoke(ctx, OpsAssistant_GetTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpsAssistantServer is the server API for OpsAssistant service.
// All implementations must embed UnimplementedOpsAssistantServer
// for forward compatibility.
type OpsAssistantServer interface {
	ExplainOrder(context.Context, *ExplainOrderRequest) (*ExplainOrderResponse, error)
	GetTimeline(context.Context, *GetTimelineRequest) (*GetTimelineResponse, error)
	mustEmbedUnimplementedOpsAssistantServer()
}

// UnimplementedOpsAssistantServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpsAssistantServer struct{}

func (UnimplementedOpsAssistantServer) ExplainOrder(context.Context, *ExplainOrderRequest) (*ExplainOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExplainOrder not implemented")
}
func (UnimplementedOpsAssistantServer) GetTimeline(context.Context, *GetTimelineRequest) (*GetTimelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimeline not implemented")
}
func (UnimplementedOpsAssistantServer) mustEmbedUnimplementedOpsAssistantServer() {}
func (UnimplementedOpsAssistantServer) testEmbeddedByValue()                      {}

// UnsafeOpsAssistantServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpsAssistantServer will
// result in compilation errors.
type UnsafeOpsAssistantServer interface {
	mustEmbedUnimplementedOpsAssistantServer()
}

func RegisterOpsAssistantServer(s grpc.ServiceRegistrar, srv OpsAssistantServer) {
	// If the following call pancis, it indicates UnimplementedOpsAssistantServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpsAssistant_ServiceDesc, srv)
}

func _OpsAssistant_ExplainOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsAssistantServer).ExplainOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsAssistant_ExplainOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsAssistantServer).ExplainOrder(ctx, req.(*ExplainOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsAssistant_GetTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsAssistantServer).GetTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsAssistant_GetTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsAssistantServer).GetTimeline(ctx, req.(*GetTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OpsAssistant_ServiceDesc is the grpc.ServiceDesc for OpsAssistant service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpsAssistant_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ops.v1.OpsAssistant",
	HandlerType: (*OpsAssistantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExplainOrder",
			Handler:    _OpsAssistant_ExplainOrder_Handler,
		},
		{
			MethodName: "GetTimeline",
			Handler:    _OpsAssistant_GetTimeline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/opsassistant/api/opspb/ops.proto",
}
